-- create a new user
CREATE ROLE language_admin WITH LOGIN CREATEDB NOINHERIT PASSWORD 'password';
-- create a new database
CREATE DATABASE language_app;
-- ensure user privileges
ALTER DATABASE language_app OWNER TO language_admin;

-- create the account table
CREATE TABLE account (
	account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    creation_date DATE NOT NULL
);

-- create the quiz table
CREATE TABLE quiz (
	quiz_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owner_id INTEGER NOT NULL,
	title TEXT NOT NULL,
    description TEXT,

    FOREIGN KEY (owner_id)
    REFERENCES account (account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID
);

-- create the entry table
CREATE TABLE entry (
	entry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INTEGER NOT NULL,
	term_a TEXT NOT NULL,
    term_b TEXT NOT NULL,
    pos TEXT,
    index INTEGER NOT NULL,

    FOREIGN KEY (parent_id)
    REFERENCES account (account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID
);